language: python

python:
  - "2.7"

cache: pip

install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy,matplotlib numpy scipy matplotlib
  - pip install sphinx==1.5.1 sphinx-bootstrap-theme==0.4.13 \
      sphinxcontrib-bibtex==0.3.4 sphinxcontrib-plantuml==0.8.1 \
      alabaster==0.7.10 MarkupSafe==0.23 html5lib==0.999 \
      Pygments==2.1.3 snowballstemmer==1.2.1 docutils==0.13.1 \
      Babel==2.3.4 requests==2.12.4 Jinja2==2.8.1 latexcodec==1.0.4 \
      pybtex==0.20.1 pybtex-docutils==0.2.1 oset==0.1.3 PyYAML==3.12

script:
  - py.test -v --color=yes --exitfirst --showlocals --durations=5
